apiVersion: ecr.services.k8s.aws/v1alpha1
kind: Repository
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: crew-dev-agents-images
  namespace: crewai
spec:
  name: crew-dev-agents/crew
  imageTagMutability: MUTABLE
  imageScanningConfiguration:
    scanOnPush: true
  lifecyclePolicy: |
    {
      "rules": [{
        "rulePriority": 1,
        "description": "Expire untagged after 7 days",
        "selection": {
          "tagStatus": "untagged",
          "countType": "sinceImagePushed",
          "countUnit": "days",
          "countNumber": 7
        },
        "action": { "type": "expire" }
      }]
    }
  tags:
    - key: Project
      value: crew-dev-agents
